# Network config
audionet:
  audionet_name: TasNet
  audionet_config:
    enc_dim: 64
    bn_dim: 64
    hidden_dim: 128
    win: 16
    layer: 6
    num_spk: 2
    module: DPRNN
    group_size: 1
    block_size: 100
    unfold: True

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: false
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioLightningModule
  gpus: [0,1,2,3]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 30
    verbose: true
  
# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 15
    factor: 0.5

# Data config
datamodule:
  data_name: LRS2DataModule
  data_config:
    train_dir: data-preprocess/LRS2Audio/tr
    valid_dir: data-preprocess/LRS2Audio/cv
    test_dir: data-preprocess/LRS2Audio/tt
    n_src: 2
    sample_rate: 16000
    fps: 25
    segment: 2.0
    normalize_audio: false
    batch_size: 2
    num_workers: 8
    pin_memory: true
    persistent_workers: false
    audio_only: true

exp:
  exp_name: dprnn_unfolded_lrs2_2mix_4gpu_bn64
