# Network config
audionet:
  audionet_name: EdgeFRCNNIterSumNOGFSA
  audionet_config:
    out_channels: 128
    in_channels: 512
    num_blocks: 16
    upsampling_depth: 5
    enc_kernel_size: 2 # ms
    num_sources: 2

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: true
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioLightningModule
  gpus: [3,4,5]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 30
    verbose: true
  
# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 15
    factor: 0.5

# Data config
datamodule:
  data_name: LRS2DataModule
  data_config:
    train_dir: DataPreProcess/WSJ0/tr
    valid_dir: DataPreProcess/WSJ0/cv
    test_dir: DataPreProcess/WSJ0/tt
    n_src: 2
    sample_rate: 8000
    fps: 25
    segment: 4.0
    normalize_audio: false
    batch_size: 1
    num_workers: 6
    pin_memory: true
    persistent_workers: false
    audio_only: true

exp:
  exp_name: EdgeFRCNNIterSumNOGFSA-in_channels=512-WSJ0-win=2ms-batch=1-gpus=3-Noncausal
