# Network config
audionet:
  audionet_name: SuDORMRFLTF
  audionet_config:
    out_channels: 128
    in_channels: 512
    num_blocks: 16
    upsampling_depth: 5
    enc_kernel_size: 21 # ms
    num_sources: 2

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: true
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioLightningModule
  gpus: [0,1,2]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 30
    verbose: true
  
# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 15
    factor: 0.5

# Data config
datamodule:
  data_name: LRS2DataModule
  data_config:
    train_dir: DataPreProcess/LRS2Audio/tr
    valid_dir: DataPreProcess/LRS2Audio/cv
    test_dir: DataPreProcess/LRS2Audio/tt
    n_src: 2
    sample_rate: 16000
    fps: 25
    segment: 2.0
    normalize_audio: false
    batch_size: 2
    num_workers: 6
    pin_memory: true
    persistent_workers: false
    audio_only: true

exp:
  exp_name: TDANetCausal-in_channels=512-LRS2-win=4ms-batch=1-gpus=3
